name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Set environment variables
    - name: Set environment variables
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}  # Use your DATABASE_URL secret
      run: |
        echo "DATABASE_URL=$DATABASE_URL" >> $GITHUB_ENV  # Set it for the next steps

    # Run migrations
    - name: Run migrations
      run: |
        python manage.py migrate --noinput

    # Collect static files
    - name: Collect static files
      run: |
        python manage.py collectstatic --noinput

    # Deploy to Vercel (assuming you have Vercel CLI configured)
    - name: Deploy to Vercel
      run: |
        vercel --prod
